### ISSUE TITLE
Cannot read property 'hide' of undefined expection on Linux

### ISSUE THREAD

**Issue by dtretyakov** [dtretyakov/teamcity-tray-notifier#12] opened 2016-06-08 19:55 UTC
```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'hide' of undefined
    at Object.<anonymous> (/home/dtretyakov/Downloads/notifier/resources/app/electron-app.js:61:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Object.<anonymous> (/home/dtretyakov/Downloads/notifier/resources/electron.asar/browser/init.js:180:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)

```

**Comment by cy6erskunk** [comment] 2016-06-09 08:22
duplicate of #11 
should be fixed now

**Closed as completed by cy6erskunk** 2016-06-09 08:22 UTC
Labels: bug, duplicate, desktop
